# Generated by Django 5.0.7 on 2024-07-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Basliq')),
                ('content', models.TextField(verbose_name='Metin')),
                ('publishingday', models.DateTimeField(auto_now_add=True, verbose_name='Tarix')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-publishingday', 'id'],
            },
        ),
    ]
